"""Every cell of the analysis notebook runs, and every chart it claims to draw appears.

[ADR 0006](../docs/decisions/0006-analysis-in-notebooks.md) puts the analysis in a
notebook and accepts that notebook code is reviewed by eye. This is the part of that
bargain which does not need an eye: a notebook that raises halfway down is not an
analysis, and nothing else in the suite would notice — the last one shipped importing six
modules that had been deleted.

Cells are exec'd into one namespace in order, which is what a kernel does minus the
kernel. That keeps the check dependency-free: an `.ipynb` is JSON, and neither `nbclient`
nor `ipykernel` is installed. What it does not check is the *output* — a cell that runs
and prints something wrong passes here. This asserts that the analysis executes, not that
it is right.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import matplotlib
import pytest

from stockout import plots

NOTEBOOK = Path(__file__).resolve().parents[1] / "notebooks" / "01_explore.ipynb"
QUESTIONS = Path(__file__).resolve().parents[1] / "docs" / "questions.md"

#: One per question. Named here rather than discovered, so a chart that silently stops
#: being drawn fails rather than reducing the count nobody was checking.
EXPECTED_FIGURES: tuple[str, ...] = (
    "q1_horizon_decay",
    "q2_store_volume",
    "q3_error_concentration",
    "q4_promotion_wake",
    "q5_classifier_vs_binned",
)


def _cells(kind: str) -> list[str]:
    notebook = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    return [
        "".join(cell["source"])
        for cell in notebook["cells"]
        if cell["cell_type"] == kind
    ]


@pytest.fixture(scope="module")
def executed(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Any]:
    """Run the whole notebook once and hand every test the namespace it left behind.

    Module-scoped because it fits twenty-odd models and a full comparison table; running
    that per test would be a minute each. The tests below only read from the namespace.
    """
    import matplotlib.pyplot as plt

    matplotlib.use("Agg")
    reports = tmp_path_factory.mktemp("reports")
    plots.REPORTS_DIR = reports  # written charts must not land in the real reports/

    # `plt.show()` on a non-interactive backend warns, and `filterwarnings = ["error"]`
    # would turn that into a failure of the cell rather than of the display it wanted.
    shown = plt.show
    plt.show = lambda *args, **kwargs: None  # type: ignore[assignment]

    namespace: dict[str, Any] = {"__name__": "__notebook__"}
    try:
        for index, source in enumerate(_cells("code")):
            try:
                exec(compile(source, f"{NOTEBOOK.name} cell {index}", "exec"), namespace)
            except Exception as exc:
                raise AssertionError(f"cell {index} of {NOTEBOOK.name} raised: {exc}") from exc
    finally:
        plt.show = shown  # type: ignore[assignment]
        plt.close("all")

    namespace["_reports"] = reports
    return namespace


def test_every_code_cell_runs(executed: dict[str, Any]) -> None:
    """The fixture is the assertion; this names it so a failure reads as one."""
    assert "prepared" in executed


def test_the_notebook_answers_on_the_committed_sample(executed: dict[str, Any]) -> None:
    """No cell may quietly fall back to an empty frame and still print a table."""
    assert executed["prepared"].rows > 0
    assert not executed["ladder"].empty
    assert len(executed["per_store"]) == executed["frame"]["store"].nunique()


def test_every_question_draws_its_chart(executed: dict[str, Any]) -> None:
    written = {path.stem for path in executed["_reports"].glob("*.png")}
    assert set(EXPECTED_FIGURES) <= written


def test_the_notebook_covers_every_committed_question() -> None:
    """The questions were committed before the analysis; the analysis must answer all of them.

    Headings are compared rather than prose, because the prose is meant to be rewritten
    and the question is not — `docs/questions.md` gaining a Q6 without a cell to answer it
    is exactly the drift this catches.
    """
    committed = set(re.findall(r"^## (Q\d)", QUESTIONS.read_text(encoding="utf-8"), re.MULTILINE))
    answered = set(re.findall(r"^## (Q\d)", "\n".join(_cells("markdown")), re.MULTILINE))
    assert committed == answered


def test_the_notebook_is_committed_without_outputs() -> None:
    """Outputs are regenerated by running it; committed ones are a diff nobody reads."""
    notebook = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    for cell in notebook["cells"]:
        assert not cell.get("outputs"), "clear outputs before committing the notebook"
